/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tosri' at '12/29/16 7:38 PM' with Gradle 3.1
 *
 * @author tosri, @date 12/29/16 7:38 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
